if(NOT DEFINED EXECUTABLE OR NOT DEFINED DESTINATION OR NOT DEFINED RUNTIME_DIR)
    message(FATAL_ERROR "EXECUTABLE, DESTINATION, and RUNTIME_DIR are required")
endif()

if(POLICY CMP0207)
    cmake_policy(SET CMP0207 NEW)
endif()

file(GET_RUNTIME_DEPENDENCIES
    EXECUTABLES "${EXECUTABLE}"
    DIRECTORIES "${RUNTIME_DIR}"
    RESOLVED_DEPENDENCIES_VAR RESOLVED_DEPENDENCIES
    UNRESOLVED_DEPENDENCIES_VAR UNRESOLVED_DEPENDENCIES
    PRE_EXCLUDE_REGEXES
        "api-ms-.*"
        "ext-ms-.*"
    POST_EXCLUDE_REGEXES
        ".*[Ww][Ii][Nn][Dd][Oo][Ww][Ss][/\\\\][Ss][Yy][Ss][Tt][Ee][Mm]32[/\\\\].*"
)

foreach(DEPENDENCY IN LISTS RESOLVED_DEPENDENCIES)
    file(COPY "${DEPENDENCY}" DESTINATION "${DESTINATION}")
endforeach()

if(UNRESOLVED_DEPENDENCIES)
    list(JOIN UNRESOLVED_DEPENDENCIES ", " UNRESOLVED_MESSAGE)
    message(WARNING "Unresolved runtime dependencies: ${UNRESOLVED_MESSAGE}")
endif()
